# External Gems
gems: 						[jekyll-paginate]


# Site Settings
title: 						"Justin Schneck"
email: 						"jschneck@mac.com"
description: 			"A collection of information gathered throught the whirlwind of my career"
baseurl: 					""
logourl: 					"/assets/img/author_image.jpg"
fa-logo: 					"fa-bookmark-o"
paginate: 				5


# Author Settings
author_name: 				"Justin Schneck"
author_bio: 				"Over the years, Justin has worked on a plethora of embedded projects from iPhone motorcycle starters to advanced brewing and distilling equipment. Recently, Justin founded Metasphere, an embedded software company primarily focused on building Bakeware and Nerves."
author_email: 				"jschneck@mac.com"
author_image: 				"/assets/img/author_image.jpg"


# Social Settings
twitter_url: 				"http://twitter.com/mobileoverlord"
github_url:  				"http://github.com/mobileoverlord"
facebook_url:  			""
youtube_url:  			""
dribbble_url:  			""
googleplus_url: 		""
instagram_url:  		""
pinterest_url:  		""
linkedin_url:  			""


# Theme Settings
theme_disqus_shortname: 	"ecko"
theme_google_comments: 		false
theme_analytics_id: 		""
theme_reading_time: 		true
theme_autoload_comments: 	false
theme_always_show_nav: 		false


# SASS Settings
# DO NOT MODIFY
sass:
 sass_dir: "assets/css/"
 style: :compressed


# Build Settings
markdown: 					kramdown
permalink: 					pretty
